apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server
spec:
  selector:
    matchLabels:
      app: graphql-server
  template:
    metadata:
      labels:
        app: graphql-server
    spec:
      containers:
        - name: hasura
          image: hasura/graphql-engine:v1.0.0-beta.2
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: dburl
                  name: graphql-server
            - name: HASURA_GRAPHQL_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: graphql-server
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: 'true'
            - name: HASURA_GRAPHQL_ENABLE_TELEMETRY
              value: 'false'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-server
spec:
  selector:
    app: graphql-server
  ports:
    - port: 80
      targetPort: 8080
